const stages={origin:"起源与制度",network:"网络与专业化",internet:"互联网浪潮",global:"全球化与反思"};
const timeline=[
{year:"1957-1960s",title:"硅谷风险投资的起点",body:"从肖克利实验室的“八叛将”出走，到仙童半导体与阿瑟·洛克，风险投资开始成为技术人逃离等级制、创办新公司的关键支撑。"},
{year:"1970s",title:"有限合伙制和专业 VC 出现",body:"投资工具从零散的富人支持，演化为有限合伙基金、董事会治理、组合投资和主动帮创业者搭团队。"},
{year:"1980s",title:"西海岸网络成为优势",body:"硅谷的流动人才、宽松竞业环境、产业集群和投资人关系网，让资本不只是钱，而是组织创新的基础设施。"},
{year:"1990s-2000s",title:"互联网把指数法则推到极致",body:"Yahoo、Google、Facebook 等案例显示，网络效应让赢家规模迅速放大，也让创始人与资本之间的权力关系发生变化。"},
{year:"2000s-2010s",title:"全球化、成长股权与独角兽时代",body:"风险投资进入中国等市场，后期资本和全球套利兴起，独角兽估值膨胀也带来 Theranos、WeWork 等反面教材。"}
];
const chapters=[
{no:"引言",stage:"origin",title:"来一场九死一生的登月式冒险",thesis:"作者用维诺德·科斯拉投资不可能食品的故事，说明风险投资的世界由指数法则支配。",points:["风险投资的收益不是平均分布，而是少数项目贡献绝大部分价值。","优秀 VC 要敢于接受看似离谱、成功概率低但上限极高的实验。","风险投资人的作用不只是预测未来，而是通过一轮轮实验去发现未来。"],cue:"讲解时可以先问：如果十个项目九个失败，一个成功一百倍，这算不算好投资？"},
{no:"第1章",stage:"origin",title:"“八叛将”集体出走，一场革命正在酝酿中",thesis:"本章把硅谷的起源放在肖克利实验室、八叛将和仙童半导体的故事里。",points:["技术人才摆脱大公司和权威控制，成为硅谷创业文化的关键开端。","阿瑟·洛克式的冒险资本让科学家有机会把实验室技术商业化。","仙童半导体不仅创造公司，也创造了人才裂变、再创业、再投资的硅谷模式。"],cue:"重点讲“解放资本”：资本让工程师敢离开稳定组织。"},
{no:"第2章",stage:"origin",title:"颠覆股权秩序，新的风险投资文化蔚然成风",thesis:"现代 VC 的制度形态开始成型：有限合伙基金、股权投资和组合思维成为主流。",points:["风险投资与银行贷款不同，它接受高失败率，用股权分享极端成功。","有限合伙制把机构资金引入早期技术公司，解决了资金来源问题。","投资人逐渐形成新风险观：不是分散到所有资产，而是在少数高潜力公司上集中下注。"],cue:"可以对比传统金融：债权追求还本付息，VC 追求少数大赢家。"},
{no:"第3章",stage:"origin",title:"亲自消除“白热化风险”，实干主义投资风格占据主导",thesis:"红杉、凯鹏华盈等机构证明，VC 不是旁观创新，而是主动塑造创新。",points:["Atari、Tandem、Genentech 等案例展示 VC 参与招聘、战略、融资和治理。","投资人要帮创始人降低关键风险，而不只是等公司自然成长。","生物科技等高不确定领域证明，风险投资可以把科学突破推向商业世界。"],cue:"这一章适合讲“hands-on VC”：钱只是入场券，真正价值是动手帮公司成型。"},
{no:"第4章",stage:"network",title:"听到关于苹果的风声了吗？现在正是投资的时机",thesis:"Apple 的案例说明，风险投资网络比单个投资工具更重要。",points:["苹果获得资金、管理经验和外部背书，逐渐从车库项目变成商业公司。","风险投资人通过互相转介绍、共享判断和共同投资扩大机会发现能力。","创业生态的优势来自网络密度：谁认识谁、谁信任谁、谁能快速调动资源。"],cue:"讲 Apple 时不要只讲乔布斯，要讲投资网络怎样帮一个产品变成公司。"},
{no:"第5章",stage:"network",title:"西海岸投资风格斩获的近40倍回报",thesis:"西海岸 VC 凭借人才流动、产业集群和关系网络，逐渐压过东海岸模式。",points:["硅谷宽松的流动文化让工程师、创始人、投资人频繁重组。","VC 网络成为发现项目、判断技术、招募团队和连接客户的高效机制。","地区优势并非天然存在，而是由制度、文化和连续成功案例共同累积。"],cue:"可以把本章概括成：硅谷不是地理名词，而是一张高密度创新网络。"},
{no:"第6章",stage:"network",title:"狂妄的雄心与有准备的头脑",thesis:"软件时代到来后，VC 的专业判断变得更重要，投资人需要比市场更早理解技术方向。",points:["投资人必须在创始人开口前就理解行业逻辑，才能识别真正的技术机会。","专业化 VC 通过研究、行业网络和深度认知，提升对新市场的判断力。","狂妄的创业愿景只有遇到有准备的资本，才可能变成可执行计划。"],cue:"这一章可用来讨论：VC 到底靠运气，还是靠准备后抓住运气？"},
{no:"第7章",stage:"internet",title:"迄今为止最大的风险投资本垒打",thesis:"Yahoo 让风险投资看到互联网的巨大回报，也考验投资人是否敢长期持有赢家。",points:["互联网公司具备快速扩张和网络效应，回报曲线比传统技术公司更陡。","早期投资人如果过早退出，会错过指数式增长的核心收益。","本章强化了幂律逻辑：真正重要的是握住少数极端赢家。"],cue:"讲这里可以强调“拿得住”也是能力，指数法则奖励耐心。"},
{no:"第8章",stage:"internet",title:"他们的公司叫作谷歌",thesis:"Google 标志着创业者权力上升，风险投资必须适应更强势的创始人。",points:["佩奇和布林拥有稀缺技术和巨大市场想象力，因此能争取更有利的融资条件。","John Doerr 等投资人提供的不只是资金，还有 CEO 人选、治理框架和战略背书。","同股不同权等安排体现了创始人与资本之间的新权力平衡。"],cue:"可把 Google 作为“创始人主权”兴起的代表案例。"},
{no:"第9章",stage:"internet",title:"反传统的风险投资模式不断涌现",thesis:"PayPal、Facebook、YC 等案例把 VC 从沙丘路的传统模式推向更开放、更反叛的形态。",points:["古怪、不合群、反共识的创始人往往更可能创造非平庸公司。","YC 通过小额、批量、社群化的方式，把创业入口变得更低、更快。","传统顶级机构开始面对新竞争者：创业者、天使、加速器都在改写规则。"],cue:"这一章适合讨论：为什么“看起来不正常”有时正是创新信号？"},
{no:"第10章",stage:"global",title:"到中国去，在那里掀起资本新浪潮",thesis:"中国证明硅谷式风险投资可以跨文化复制，但也会被本土市场重新塑造。",points:["西方资本把 VC 方法带到中国早期互联网市场，支持百度、阿里、腾讯等公司成长。","沈南鹏、徐新等本土投资人逐渐成为主导力量，形成中国自己的项目发现和执行方式。","中国市场规模、速度和竞争强度，让风险投资的指数法则表现得更加剧烈。"],cue:"讲这一章时可以联系中国互联网：VC 不是外来标签，而是被本土化的增长机制。"},
{no:"第11章",stage:"internet",title:"Facebook 搅动投资风云",thesis:"Facebook 案例展现了投资团队协作、判断速度和内部机制的重要性。",points:["科技泡沫后行业低迷，但真正的大机会往往出现在市场情绪最差的时候。","Accel 的 Facebook 投资说明，顶级交易需要团队信任和快速决策。","风险投资是团队运动，内部失灵会让机构错过最重要的机会。"],cue:"可以用反差开场：在行业寒冬里，为什么反而出现了最重要的投资？"},
{no:"第12章",stage:"global",title:"成长股权兴起，“全球套利”时代来临",thesis:"后期资本、全球资金和成长股权改变了创业公司的融资节奏与估值逻辑。",points:["Facebook 等成熟创业公司吸引全球资本，融资不再只依赖传统早期 VC。","投资人开始用增量利润、规模效应和全球比较来判断公司的未来价值。","资本充裕让好公司有更久的私人市场成长空间，也抬高了进入门槛。"],cue:"这一章可解释为什么很多公司上市更晚、估值更高、私募轮更多。"},
{no:"第13章",stage:"network",title:"是什么让红杉资本不断取得成功",thesis:"红杉的成功不是单次好运，而是有意识地设计组织、网络和传承机制。",points:["顶级 VC 会主动创造好运：长期积累声誉、信息流和创始人信任。","机构化能力让红杉可以跨周期、跨行业、跨代际保持竞争力。","优秀投资组织既要保持个人判断力，也要把经验沉淀为团队系统。"],cue:"可以把红杉作为案例讲：风险投资公司本身也是需要被经营的产品。"},
{no:"第14章",stage:"global",title:"当音乐停止时，硅谷面临一场洗牌",thesis:"独角兽时代暴露了风险投资的阴影：后期估值泡沫、治理失灵和社会争议。",points:["Theranos、Zenefits、WeWork 等案例说明，资本可能放大叙事，也可能纵容失控。","闪电式扩张适合少数网络效应公司，但被滥用后会制造浪费和治理风险。","作者承认 VC 的社会价值，同时提醒行业必须面对多样性、监管和责任问题。"],cue:"结尾讨论不要只批判 VC，也要区分早期创新资本和鲁莽后期资本。"},
{no:"结尾",stage:"global",title:"风险投资的价值与边界",thesis:"风险投资已经证明自己是支持创新型年轻公司的强大制度，但它不是无条件正确。",points:["VC 能打破既有企业权力，推动新技术挑战旧巨头。","行业需要改善封闭圈层和多样性不足，否则会限制它理解未来的能力。","最好的总结是：风险投资不能预测未来，却能资助足够多的实验，让未来出现。"],cue:"最后可抛出问题：如果未来无法预测，我们应该怎样配置资源？"}
];
function renderTimeline(){const root=document.querySelector("#timelineList");root.innerHTML=timeline.map(item=>`<article class="timeline-item"><time>${item.year}</time><div><h3>${item.title}</h3><p>${item.body}</p></div></article>`).join("");}
function renderChapters(){const query=document.querySelector("#chapterSearch").value.trim().toLowerCase();const filter=document.querySelector("#chapterFilter").value;const root=document.querySelector("#chapterGrid");const filtered=chapters.filter(chapter=>{const stageMatch=filter==="all"||chapter.stage===filter;const text=[chapter.no,chapter.title,chapter.thesis,chapter.points.join(" "),chapter.cue].join(" ").toLowerCase();return stageMatch&&(!query||text.includes(query));});root.innerHTML=filtered.map(chapter=>`<article class="chapter-card"><div class="chapter-meta"><span>${chapter.no}</span><span class="chapter-tag">${stages[chapter.stage]}</span></div><h3>${chapter.title}</h3><p>${chapter.thesis}</p><ul>${chapter.points.map(point=>`<li>${point}</li>`).join("")}</ul><div class="chapter-note">${chapter.cue}</div></article>`).join("");if(!filtered.length){root.innerHTML=`<p class="empty-state">没有找到匹配的章节，可以换个关键词试试。</p>`;}}
renderTimeline();renderChapters();document.querySelector("#chapterSearch").addEventListener("input",renderChapters);document.querySelector("#chapterFilter").addEventListener("change",renderChapters);
